@startuml
@startuml
package "asyncapi-tools Github Repository" {
  [asyncapi-tools] ..> [Ballerina Platform] : Maintained by
  
  package "AsyncAPI" {
    [AsyncAPI Specification] --> [open-source tools] : Includes
  }

  component "Ballerina Language" as Ballerina {
     [Ballerina Services] --> [AsyncAPI Specification] : Generated for 
  }

  [Ballerina Services] --> [Ballerina Language]
  [asyncapi-tools] --> [AsyncAPI]
  [asyncapi-tools] --> [Ballerina]

  component "Compiler Plugin" {
    [Service Validation] --> [AsyncAPI Specification] : Validates against
  }

  [Compiler Plugin] --> [Ballerina]

  [Instructions] --> [asyncapi-tools]
  [Examples] --> [Instructions]

}
@enduml
@enduml