@startuml
@startuml
package "EMBC ESS" {
  [Contribution Guidelines]
  [Code of Conduct]
  [Readme]
  [License]
  
  package "Backend" {
    [ASP.NET Core]
  }
  
  package "Frontend" {
    [Angular]
  }
  
  [Docker]
  [Jenkins]
}

note bottom of [License]
:Apache License 2.0:
end note

[ASP.NET Core] ..> [Docker] : Deployed Using
[Angular] ..> [Docker] : Deployed Using
[Docker] ..> [Jenkins] : CI/CD
@enduml
@enduml