@startuml
@startuml
package "https://github.com/gdsc-ys/mlops/" {
  [gdsc-ys] ..> [mlops]
  package "mlops" {
    [Machine Learning Operations (MLOps)]
    [Jupyter notebook]
  }
  [gdsc-ys] --> [Machine Learning Operations (MLOps)]
  [Jupyter notebook] ..> [Machine Learning Operations (MLOps)]
}
@enduml
@enduml