@startuml
@startuml
package "youtube-dl-nas" {
  [Docker]
  [Shell Script]
  [Setup Instructions]
  [Usage Examples]
}

actor "hyeonsangjeon" as A

A -- [youtube-dl-nas]
[youtube-dl-nas] ..> [Docker] 
[youtube-dl-nas] ..> [Shell Script]
[youtube-dl-nas] ..> [Setup Instructions]
[youtube-dl-nas] ..> [Usage Examples]

@enduml
@enduml