@startuml
```plantuml
@startuml
!pragma teoz true
' uncomment the line below if you're targeting version 1.20 or later
' !pragma layout smetana
'Azure
' uncomment the line below if you're targeting version 1.20 or later
' !include <azure/AzureCommon>
' uncomment the line below if you're targeting version 1.20 or later
' !include <azure/Compute/AppService>

node "React Frontend" {
  [App.js]
  [index.js]
  package.json
  [Components]
  [Redux]
  [Utils]
}

package Components {
    [BountyCard.js]
    [BountyDetails.js]
    [CreateBountyForm.js]
    [UserProfile.js]
    [WalletConnect.js]
}

package Redux {
    [actions/]
    [reducers/]
    [store.js]
}

package actions {
    [fetchBounties]
    [submitSolution]
    [updateUserProfile]
}

package reducers {

}

package Utils {

}


node "Backend API (Not Fully Shown)" {
  [API Endpoints]
  [Authentication]
  [Data Storage]
}

node "Ethereum Blockchain" {
  [Smart Contracts]
  [MTX Tokens]
}

App.js -- Components
index.js -- App.js
index.js -- Redux
Redux -- actions
actions -- Backend API (Not Fully Shown) : Uses
Backend API (Not Fully Shown) -- Ethereum Blockchain : Interacts With
WalletConnect.js -- Ethereum Blockchain : Interacts With
@enduml
```
@enduml