@startuml
@startuml
title MatryxPlatform Component Diagram

package "MatryxPlatform" {
  [MatryxPlatform] ..> [Ethereum blockchain] : operates on
  [MatryxPlatform] ..> [MTX token] : uses
  [MatryxPlatform] ..> [JavaScript] : written in
  [MatryxPlatform] ..> [STEM] : incentivize
  [MatryxPlatform] ..> [Documentation] : guides
}

@enduml
@enduml