@startuml
@startuml
title Jseats Repository Structure

package "jseats" {
    [jseats]
    [documentation]
}

actor PauMinoves as "Pau Minoves"
actor User

PauMinoves --> [jseats] : manages
User --> [jseats] : uses
User --> [documentation] : reads

class jseats {
    +D'Hondt()
    +Sainte-Laguë()
    +Modified Sainte-Laguë()
    +Huntington-Hill()
    ..
    +Other methods()
  }
@enduml
@enduml