@startuml
@startuml
title jseats Component Diagram

package "jseats" {
  [jseats]
}

cloud "GitHub" {
  [GitHub Repository]
}

[User] --> [GitHub Repository] : Clones/Modifies/Contributes
[GitHub Repository] --> [jseats] : Contains
[jseats] ..> [D'Hondt]
[jseats] ..> [Sainte-Laguë]
[jseats] ..> [Largest remainder]
[jseats] ..> [Imperiali]
[jseats] ..> [Guide]

[User] --> [jseats] : Uses
@enduml
@enduml