@startuml
```plantuml
@startuml
!define AWESOMEFONTURL https://raw.githubusercontent.com/FortAwesome/Font-Awesome/6.x/raw/main/svgs/
!define DEVICONSURL https://raw.githubusercontent.com/devicons/devicon/master/icons/

skinparam componentStyle uml2
skinparam rectangleStyle uml2

component "index.php\n(Front Controller)" as IndexPHP
component "Router\n(system/core/Router.php)" as Router
component "Output\n(system/core/Output.php)" as Output

package "CodeIgniter Framework\n(system/)" {
  component "Core\n(system/core/)" as Core {
    component "CI_Controller" as CI_Controller
    component "CI_Model" as CI_Model
    component "CI_Config" as CI_Config
    component "CI_Loader" as CI_Loader
  }
  component "Database\n(system/database/)" as Database
  component "Helpers\n(system/helpers/)" as Helpers
  component "Libraries\n(system/libraries/)" as Libraries
  component "Language\n(system/language/)" as Language

}

package "Application\n(application/)" {
  component "Controllers\n(application/controllers/)" as Controllers {
      component "ctusuario.php" as ctusuario
  }
  component "Models\n(application/models/)" as Models {
        component "business/" as business
        component "DAO/" as DAO
        component "Entities/" as Entities
        component "facade/" as facade
        component "factoryBusiness.php" as factoryBusiness
        component "factoryDAO.php" as factoryDAO
  }
  component "Views\n(application/views/)" as Views {
      component "usuario/" as usuario
      component "welcome_message.php" as welcome_message
  }
  component "Configurations\n(application/config/)" as Configurations {
        component "autoload.php" as autoload
        component "config.php" as config
        component "database.php" as database
  }
  component "Language Files\n(application/language/)" as ApplicationLanguage
  component "Libraries\n(application/libraries/)" as ApplicationLibraries {
        component "ObjGeneric.php" as ObjGeneric
  }
  component "Third-Party Libraries\n(application/third_party/)" as ThirdPartyLibraries
}

package "Assets\n(assets/)" {
  component "JavaScript\n(assets/js/)" as JavaScript {
      component "jquery.js" as jquery
      component "price_format.js" as price_format
  }
}

IndexPHP --> Router : Routes Request
Router --> Controllers : Invokes Controller
Controllers --> Models : Interacts with Models
Controllers --> Views : Loads View
Controllers --> ApplicationLanguage : Loads language
Controllers --> Configurations : Reads application settings
Controllers --> ApplicationLibraries : Uses application specific libraries
Views --> Assets : Uses Assets (CSS, JS, Images)
Models --> Database : Data Access
IndexPHP --> CI_Config : Initializes Configuration
IndexPHP --> CI_Loader : Loads Resources
Views --> Output : Generates Output
ThirdPartyLibraries -- Models : May use

Controllers ..> CI_Controller : Extends
Models ..> CI_Model : Extends

note top of Core : Core CodeIgniter Classes

note top of Application : Application Specific Code

@enduml
```
@enduml