@startuml
```plantuml
@startuml HomeSensorHub Component Diagram

package "HomeSensorHub" {
  [homesensorhub.py] as MainApp
  [__main__.py] as MainEntry
  [utils.logging] as Logging
  [routing.payload] as Payload
  [routing.sensor_sink] as SensorSink
  [sensors.probe] as SensorProbe
  package "routing" {
    [routing.data_sender] as DataSender
    [routing.mqtt] as MQTT
    [routing.mqtt_sender] as MQTTSender
    [routing.mqtt_subscriber] as MQTTSubscriber
  }
  package "sensors" {
    [sensors.sensor_types] as SensorTypes
    package "BoschBME" {
      [sensors.BoschBME.probe] as BoschBMEProbe
      package "BoschBME280" {
        [sensors.BoschBME.BoschBME280.probe] as BoschBME280Probe
        [sensors.BoschBME.BoschBME280.type] as BoschBME280Type
      }
      package "BoschBME680" {
        [sensors.BoschBME.BoschBME680.probe] as BoschBME680Probe
        [sensors.BoschBME.BoschBME680.type] as BoschBME680Type
      }
    }
    package "RCWL0515" {
      [sensors.RCWL0515.probe] as RCWL0515Probe
      [sensors.RCWL0515.driver] as RCWL0515Driver
    }
    package "TSL258x" {
      [sensors.TSL258x.probe] as TSL258xProbe
      [sensors.TSL258x.driver] as TSL258xDriver
      [sensors.TSL258x.type] as TSL258xType
    }
  }
}

MainEntry -- MainApp
MainApp -- Logging : uses
MainApp -- SensorSink : uses
MainApp -- SensorProbe : uses
MainApp -- MQTTSender : uses
MainApp -- MQTTSubscriber : uses
SensorSink -- Payload : uses
SensorProbe -- SensorTypes : uses
MQTTSender -- MQTT : uses
MQTTSender -- Payload : uses
MQTTSubscriber -- MQTT : uses

SensorProbe <|-- BoschBMEProbe
SensorProbe <|-- RCWL0515Probe
SensorProbe <|-- TSL258xProbe
BoschBMEProbe <|-- BoschBME280Probe
BoschBMEProbe <|-- BoschBME680Probe

RCWL0515Probe -- RCWL0515Driver : creates
TSL258xProbe -- TSL258xDriver : creates
TSL258xProbe -- TSL258xType : creates

SensorTypes <|-- BoschBME280Type
SensorTypes <|-- BoschBME680Type
SensorTypes <|-- TSL258xType
@enduml
```
@enduml